all:
  children:
    webservers:
      hosts:
        web1:
          ansible_host: 158.160.186.55
          ansible_user: sudosu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_ya
        web2:
          ansible_host: 158.160.177.112
          ansible_user: sudosu
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519_ya
